name: myapp
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  url_launcher: ^6.2.4
  permission_handler: ^11.0.1

  google_generative_ai: ^0.4.6
  file_picker: ^9.2.3
  speech_to_text: ^7.0.0


  cupertino_icons: ^1.0.6
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.1.4
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.5
  provider: ^6.1.1
  http: ^1.2.0
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/video_editing.jpg
    - assets/thumbnail_design.jpg
    - assets/uiux.jpg
    - assets/mobile_dev.webp
    - assets/medical_assistant.jpeg
    - assets/farming.jpg
    - assets/electrician.jpg
    - assets/plumber.jpeg
    - assets/flutter_dev.png
    - assets/uiux.jpeg
    - assets/marketing.png
    - assets/hr.jpeg
    - assets/background.jpg
    - assets/logo.png